### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by Ro-meo** [incentius-foss/WhatTheDuck#5]
- It would be nice to run this beautiful functionality on a local docker environment 
- Especially in Europe with GDPR and in the context of securing your data this would be very welcome to have run locally 

- To have a docker-compose.yaml file in the repository as an example

- I tried other way but couldn't get it to work as intended (on a raspberry pi5)

- None

**Comment by pratikpatel-aurochs** [comment]
@Ro-meo  In this context, GDPR doesn't apply, your data stays strictly within your browser without being uploaded anywhere else

**Comment by Ro-meo** [comment]
thanx for the GDPR reply.
Any directions/views regarding a docker-compose version ?

**Comment by pratikpatel-aurochs** [comment]
@Ro-meo https://github.com/incentius-foss/WhatTheDuck/pull/6

**Comment by Ro-meo** [comment]
Tested it on a rpi5
it works.. Thank you!
