### ISSUE TITLE
[vite] server connection lost. polling for restart...

### ISSUE THREAD

**Issue by floviolleau** [incentius-foss/WhatTheDuck#7]
Thanks for this amazing tool!

**Describe the bug**
Page is always rebooting

`[vite] server connection lost. polling for restart...`

**To Reproduce**
1. Install with docker
2. Change port 9000 to 16000 in docker-compose.yaml
3. Try to use

**Expected behavior**
Normal behavior

**Screenshots**
https://github.com/incentius-foss/WhatTheDuck/assets/5442973/9c583460-5a89-4cd6-b06d-79b46b25e1c3

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Browser: Firefox
 - Version: 127.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pratikpatel-aurochs** [comment]
Hi @floviolleau, 

It should work I'm not sure may bi 16000 is used somewhere else as well?

Thanks,
Pratik Patel

**Comment by floviolleau** [comment]
Hi,

I took randomly 16000. It can be another random one and be configurable.

9000 is already in use on me side so I wanted to easily change it.

Kind regards.

**Comment by pratikpatel-aurochs** [comment]
> Hi,
> 
> I took randomly 16000. It can be another random one and be configurable.
> 
> 9000 is already in use on me side so I wanted to easily change it.
> 
> Kind regards.

Can you change to any other port and see if it works ?

**Comment by lgwapnitsky** [comment]
I'm having this issue with port 9000.
