### ISSUE TITLE
[FEATURE] Page size

### ISSUE THREAD

**Issue by floviolleau** [incentius-foss/WhatTheDuck#8]
**Describe the solution you'd like**
Having a page size available with the pagination and be able to set default to a specific size.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pratikpatel-aurochs** [comment]
Hi @floviolleau,

Page selection option is available now.

Demo - https://whattheduck.incentius.com/

Thanks,

<img width="434" alt="Screenshot 2024-07-12 at 5 28 13 PM" src="https://github.com/user-attachments/assets/9fc0c2d8-58cc-4381-b87d-83c63a6c9c69">
